### ISSUE TITLE
[Suggestion] Matching Particle Colors

### ISSUE THREAD

**Issue by Zartrix** [lamaprogramer/BetterPotionVisuals#1]
I noticed that the particles surrounding the player or on the ground when coming from a splash or lingering potion still use the “old” colors instead of the ones that the potion has.
I hope that this is something that can be considered to be added!

**Comment by williamk-jr** [comment]
Interesting, didn’t notice that, I’ll try and fix that as soon as I get the chance😁

**Comment by williamk-jr** [comment]
What Minecraft version are you using? And do you have any other mods installed? I can't seem to replicate your problem, so I'm wondering if a mod or mod loader is causing problems.

**Comment by Zartrix** [comment]
I thought it just wasn't implemented, oops. I'll try to find out which mod causes the issue and report back. Sorry for the inconvenience.

**Comment by Zartrix** [comment]
Okay, this resolved way quicker than I thought. I was using Quilt 0.18.3 and updated to 0.18.4 just after my response, so I guess that was the problem. Again, sorry for the false report/suggestion.

**Comment by williamk-jr** [comment]
Nah, don't worry about it man, I thank you for the suggestion anyways
